require: sudo
language: node_js
node_js:
  - 6
services:
  - docker
env:
  - DOCKER_IMAGE=prodest/api-ceturb SERVICE_NAME=api-ceturb RANCHER_URL=http://rancher.dcpr.es.gov.br/v1/projects/1a2032 RANCHER_STACK=api RANCHER_COMPOSE_URL=http://rancher.dcpr.es.gov.br/v1/projects/1a2032/environments/1e101/composeconfig
script: 
  /bin/sh .travis.sh
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh .deploy.sh
  on:
    branch: master
